namespace SklepAsp.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ProdyctIdAutoGenerated : DbMigration
    {
        public override void Up()
        {
            DropPrimaryKey("dbo.Products");
            AlterColumn("dbo.Products", "ProductId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.Products", "ProductId");
        }
        
        public override void Down()
        {
            DropPrimaryKey("dbo.Products");
            AlterColumn("dbo.Products", "ProductId", c => c.String(nullable: false, maxLength: 128));
            AddPrimaryKey("dbo.Products", "ProductId");
        }
    }
}
